apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qzkr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qzkr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qzkr
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qzkr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qzkr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ndxq-tenant/rhtap-demo-app/hacbs-test-project-qzkr@sha256:8efcecc0325ae226d32f1d22eb65b188c2b0cb30c29ceb8a85f4202b9bb25342
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
